kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: dotnetkonf-noc
spec:
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  template:
    metadata:
      labels:
        app: dotnetkonf-noc
    spec:
      restartPolicy: Always
      containers:
        - name: dotnetkonf-noc
          image: selcukusta/dotnetkonf-sample-no-cert:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              memory: "200Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: dotnetkonf-noc
  labels:
    name: dotnetkonf-noc
spec:
  type: ClusterIP
  selector:
    app: dotnetkonf-noc
  ports:
    - port: 80
      name: http
      targetPort: 80
